### ISSUE TITLE
toolyon.com

### ISSUE THREAD

**Issue by ghost** [osm-fr/attributions#379]
GitHub is a problematic platform, see https://sfconservancy.org/blog/2022/jun/30/give-up-github-launch/, consider using an open-source alternative, like a one based on Forgejo: Codeberg.

**Comment by NathanBnm** [comment]
Contacté le 10/04/25 à l'adresse colliot@pierre-jean.com (adresse indiquée dans les mentions légales du site)

**Comment by ElementW** [comment]
Complètement intentionnel, le bloc étant pourtant bien créé par Leaflet.

`https://www.toolyon.com/plugins/toolyon/squelette_toolyon/css/carte.css` ([archive.is](https://archive.is/M37UU)):
```css
/* Boutons de zoom */
.leaflet-top .leaflet-control {} 


.leaflet-touch .leaflet-control-attribution {display:none;}
```

Site édité par l'agence [[Webvaloris](https://webvaloris.fr/)]. Aucune mention d'OSM dans les mentions légales non plus.
